version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_painel
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Painel
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql

volumes:
  mysql_data:
